# ---------------------------------------------------------
# msp_cloud_acronyms.py
# Author: Julia Wen (wendigilane@gmail.com)
# Date: 10-10-2025
#
# Description: MSP and Cloud related acronyms
#
# ---------------------------------------------------------


ACRONYMS = {
    "AIOps": "AI for IT Operations",
    "AI-Driven Security": "Security operations enhanced with AI/ML analytics, threat detection, and automated remediation, including Azure Defender for Cloud, AWS Security Hub with GuardDuty integration",
    "API": "Application Programming Interface",
    "App Protection Policies": "Azure endpoint/app protection policies",
    "Azure AD": "Azure Active Directory",
    "BCP": "Business Continuity Planning",
    "Blob Storage": "Azure object storage",
    "BYOK": "Bring Your Own Key (Encryption)",
    "CAPEX": "Capital Expenditure",
    "CI/CD": "Continuous Integration / Continuous Deployment",
    "CMMC 2.0": "Cybersecurity Maturity Model Certification version 2.0 — maturity framework for protecting controlled unclassified information (CUI) in the US, relevant to Azure and AWS compliance",
    "CloudHSM": "AWS Hardware Security Module",
    "CloudTrail": "AWS API call logging service",
    "Cognito": "AWS app authentication service",
    "Conditional Access": "Azure access policy engine for authentication/authorization",
    "CSP": "Cloud Service Provider",
    "Data Lake": "Azure Data Lake storage",
    "Defender": "Microsoft Defender for endpoint security",
    "Defender for Endpoint": "Microsoft endpoint protection service",
    "DevOps": "Development + Operations",
    "Disk Encryption": "Azure Disk Encryption",
    "DDoS Protection": "Distributed Denial-of-Service mitigation",
    "DRaaS": "Disaster Recovery as a Service",
    "EDR": "Endpoint Detection and Response — monitors endpoints for threats; Azure Defender for Endpoint, AWS GuardDuty + Security Hub",
    "Entra ID": "Azure Active Directory identity service",
    "FedRAMP": "Federal Risk and Authorization Management Program",
    "FinOps": "Cloud Financial Operations",
    "Firewall": "Azure Firewall",
    "GANTT": "Gantt Chart — project schedule visualization",
    "Glacier": "AWS long-term archival storage",
    "GPUaaS": "GPU as a Service",
    "GuardDuty": "AWS threat detection service",
    "HLD": "High-Level Design Document",
    "HIPAA": "Health Insurance Portability and Accountability Act",
    "IAM": "Identity & Access Management",
    "IaC": "Infrastructure as Code",
    "IaaS": "Infrastructure as a Service",
    "Inspector": "AWS vulnerability assessment tool",
    "ISO 27001": "Information Security Management Standard",
    "Key Management Service (KMS)": "AWS key management service",
    "Key Vault": "Azure Key Vault",
    "KPI": "Key Performance Indicator",
    "LLD": "Low-Level Design Document",
    "Log Analytics": "Azure log analytics service",
    "Macie": "AWS data privacy & security monitoring",
    "MDR": "Managed Detection and Response — outsourced monitoring and incident response, e.g., Azure Sentinel MDR, AWS Security Hub MDR",
    "Microsoft Defender": "Microsoft security and threat protection",
    "ML Ops": "Machine Learning Operations",
    "MSP": "Managed Service Provider",
    "NACL": "Network Access Control List (AWS)",
    "NOC": "Network Operations Center",
    "NSG": "Network Security Group (Azure)",
    "OAuth": "Open Authorization standard",
    "OIDC": "OpenID Connect protocol",
    "OPEX": "Operational Expenditure",
    "PaaS": "Platform as a Service",
    "PERT": "Program Evaluation Review Technique",
    "PRINCE2": "Projects in Controlled Environments, Version 2",
    "RBAC": "Role-Based Access Control",
    "RACI": "Responsible, Accountable, Consulted, Informed",
    "RMM": "Remote Monitoring & Management",
    "ROI": "Return on Investment",
    "S3": "AWS Simple Storage Service",
    "SaaS": "Software as a Service",
    "SAML": "Security Assertion Markup Language",
    "SecOps": "Security Operations",
    "Security Group": "AWS virtual firewall for instances",
    "Security Hub": "AWS central security management",
    "Sentinel": "Azure SIEM",
    "Shield": "AWS Shield (DDoS Protection)",
    "SIEM": "Security Information and Event Management",
    "SLA": "Service Level Agreement",
    "SOC": "Security Operations Center",
    "SSE-C": "Server-Side Encryption with Customer-provided keys (AWS)",
    "SSE-KMS": "Server-Side Encryption with KMS-managed keys (AWS)",
    "SSE-S3": "Server-Side Encryption with S3-managed keys (AWS)",
    "SSO": "Single Sign-On — Azure AD SSO, AWS SSO for enterprise applications",
    "SPI": "Schedule Performance Index — PM metric",
    "VAC": "Variance at Completion — PM metric",
    "VPC": "Virtual Private Cloud (AWS)",
    "VNet": "Virtual Network (Azure)",
    "VPN": "Virtual Private Network",
    "WAF": "Web Application Firewall",
    "WBS": "Work Breakdown Structure",
    "XDR": "Extended Detection & Response — unified threat detection and response across endpoints, identities, apps, and cloud; Azure Defender XDR, AWS GuardDuty + Security Hub XDR"
}

